plugin: yaml
inventory:
  all:
    children:
      arista_switches:
        hosts:
          leaf1:
            ansible_host: 10.10.10.2
        vars:
          ansible_connection: network_cli
          ansible_network_os: arista.eos.eos
          ansible_user: admin
          ansible_password: admin
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
